---
title: 'Lab 4'
author: "Yijing Lu"
date: 'Oct 8 2018'
output:
  pdf_document:
    latex_engine: xelatex
    includes:
    toc: yes
    number_sections: yes
    keep_tex: yes
header-includes: 
- \usepackage{graphicx}
- \usepackage{float}
---
```{r options, include=FALSE}
knitr::opts_chunk$set(cache=TRUE, error=FALSE, message=TRUE, warning=TRUE)
isSolution = TRUE
seeResults = 'hide'
```

# Using ggplot function to recreate the graph
```{r}
x <- seq(-3, 3, by = 0.01)
y <- dnorm(x, mean = 0, sd = 1)

shift = 3.2
x2 <- seq(0, 6, by = 0.01)
y2 <- dnorm(x2, mean=shift, sd = 1)

coord.x <- c(qnorm(0.95), seq(qnorm(0.95), 0, by=-0.01), 0)
coord.y <- c(0, dnorm(coord.x[-c(1, length(coord.x))], mean=3.2), 0)

coord.x2 <- c(qnorm(0.95), seq(qnorm(0.95), 3, by=0.01), 3)
coord.y2 <- c(0, dnorm(coord.x2[-c(1, length(coord.x2))]), 0)

ggplot() +
    geom_line(aes(x, y), col = 4, lwd = 1) +
    geom_line(aes(x2, y2), col = 2, lwd = 1) +
    geom_polygon(aes(coord.x, coord.y, fill = "col2"), col = "black") +
    geom_polygon(aes(coord.x2, coord.y2, fill = "col1"), col = "black") +
    scale_fill_manual(values = c(col1=rgb(0, 0, 1, 0.5), col2=rgb(1, 0, 0, 0.5)),
          label = c("Type I error", "Type II error")) +
    annotate("text", x = 1.1, y = 0.02, label = expression(beta), size = 4.5) +
    annotate("text", x = 2, y = 0.02, label = expression(alpha),
             col = "white", size = 4.5) + 
    scale_x_continuous(breaks = c(0, 3), 
          labels = c(expression(theta[0]), expression(theta[a]))) +
    geom_vline(xintercept = qnorm(0.95), linetype = 2, lwd = 1) +
    theme(text = element_text(size = 18),
          axis.title = element_blank(), 
          axis.ticks.x = element_line(size = 0.5),
          axis.text.y = element_text(angle = 90, hjust = 0.5, vjust = 3, size = 14),
          panel.background = element_blank(),
          panel.border = element_rect(colour = "black", fill = NA, size = 1),
          legend.position = c(0, 1),
          legend.margin = margin(c(5, 5, 5, 5)),
          legend.justification = c(0,1),
          legend.background = element_rect(color = "black", 
          fill = NA, size = .5, linetype = "solid"),
          legend.text = element_text(size = 12, margin = margin(t = 0, l = 12, r = 3, b = 0)),
          legend.title=element_blank())

```

# Check if a given positive integer is a prime number.
```{r}
isPrime <- function(x) {
    if(x == 1) return(FALSE)
    i <- 2
    while(i * i <= x) {
        if(x %% i == 0) return(FALSE)
        i = i + 1
    }
    return(TRUE)
}
```

```{r}
isPrime(1)
isPrime(2)
isPrime(7)
isPrime(9)
```


